@extends('layouts.layout')
@section('content')
@include('sections.header')

<main id="trainings">
    <div id="training-events" class="container my-5">
        <div class="col-lg-12">
            <!-- Top Sliding Image Gallery with Buttons -->
            <div class="row justify-content-center mb-3">
                <div class="col-1 d-flex align-items-center">
                    <button id="slide-left" class="btn btn-primary" disabled>Left</button>
                </div>
                <div class="col-10">
                    <div class="sliding-gallery-wrapper">
                        <div class="sliding-gallery">
                            <!-- Top Sliding Images/Articles will be generated by script -->
                        </div>
                    </div>
                </div>
                <div class="col-1 d-flex align-items-center">
                    <button id="slide-right" class="btn btn-primary">Right</button>
                </div>
            </div>
            
            <div class="row justify-content-center">
                <div class="main-image text-center">
                    <div class="image-header" style="background-color: rgba(255, 255, 255, 0.8); padding: 5px;">
                        <h3>Header of Main Image</h3>
                    </div>
                    <img id="main-image" src="image2.jpg" alt="Main Image" class="img-fluid">
                </div>
            </div>
            
            <!-- Bottom Sliding Images -->
            <div class="row">
                <div class="col-lg-12"><div class="image-wrapper-container">
                    <div class="image-wrapper">
                        <!-- Bottom Sliding Images will be dynamically generated -->
                        <div class="image-wrapper">
                            <!-- Bottom Sliding Images will be generated by script -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        const articleData = [
            { src: 'article1.jpg', title: 'Article 1', description: 'This is the first article.' },
            { src: 'article2.jpg', title: 'Article 2', description: 'This is the second article.' },
            { src: 'article3.jpg', title: 'Article 3', description: 'This is the third article.' },
            { src: 'article4.jpg', title: 'Article 4', description: 'This is the fourth article.' }
        ];

        const imageSources = [
            'image1.jpg', 
            'image2.jpg', 
            'image3.jpg', 
            'image4.jpg', 
            'image5.jpg', 
            'image6.jpg', 
            'image7.jpg'
        ];

        // Generate top sliding images/articles
        const gallery = document.querySelector('.sliding-gallery');
        articleData.forEach(article => {
            const articleDiv = document.createElement('div');
            articleDiv.className = 'gallery-article';
            articleDiv.innerHTML = `
                <img src="${article.src}" alt="${article.title}" class="gallery-image">
                <div class="article-info">
                    <h4>${article.title}</h4>
                    <p>${article.description}</p>
                </div>
            `;
            gallery.appendChild(articleDiv);
        });

        // Generate bottom sliding images
        const wrapper = document.querySelector('.image-wrapper');
        imageSources.forEach(src => {
            const img = document.createElement('img');
            img.src = src;
            img.alt = `Image ${src.charAt(src.length - 5)}`;
            img.className = 'sliding-image';
            wrapper.appendChild(img);
        });

        const images = document.querySelectorAll('.sliding-image');
        const mainImage = document.getElementById('main-image');
        const galleryArticles = document.querySelectorAll('.gallery-article');
        const totalImages = images.length;
        const totalGalleryArticles = galleryArticles.length;
        let currentIndex = 0;
        let galleryIndex = 0;

        function slideImages() {
            const containerWidth = document.querySelector('.image-wrapper-container').offsetWidth;
            const imageWidth = containerWidth / 3; // 3 images visible
            const totalWidth = imageWidth * totalImages;

            wrapper.style.transition = 'transform 1s ease';
            wrapper.style.transform = `translateX(-${currentIndex * imageWidth}px)`;

            // Calculate the index of the middle image
            const middleIndex = (currentIndex + 1) % totalImages;

            // Update the main image based on the middle image
            mainImage.src = images[middleIndex].src;
            mainImage.alt = images[middleIndex].alt;

            currentIndex = (currentIndex + 1) % totalImages;

            if (currentIndex === 0) {
                setTimeout(() => {
                    wrapper.style.transition = 'none';
                    wrapper.style.transform = 'translateX(0)';
                }, 1000); // Reset transition after slide completion
            }
        }


        setInterval(slideImages, 2000); // Adjust interval as needed

        function updateGalleryPosition() {
            gallery.style.transition = 'transform 0.5s ease';
            gallery.style.transform = `translateX(-${galleryIndex * 100}%)`;

            // Disable/Enable buttons based on the gallery position
            document.getElementById('slide-left').disabled = (galleryIndex === 0);
            document.getElementById('slide-right').disabled = (galleryIndex === totalGalleryArticles - 1);
        }

        document.getElementById('slide-left').addEventListener('click', function() {
            if (galleryIndex > 0) {
                galleryIndex--;
                updateGalleryPosition();
            }
        });

        document.getElementById('slide-right').addEventListener('click', function() {
            if (galleryIndex < totalGalleryArticles - 1) {
                galleryIndex++;
                updateGalleryPosition();
            }
        });

        // Initial button state
        updateGalleryPosition();
    });
    </script>

    <style>
    .sliding-gallery-wrapper {
        overflow: hidden;
        width: 100%;
    }

    .sliding-gallery {
        display: flex;
        transition: transform 0.5s ease;
    }

    .gallery-article {
        flex: 0 0 100%;
        text-align: center;
        padding: 10px;
    }

    .gallery-image {
        max-width: 100%;
        height: auto;
        margin-bottom: 10px;
    }

    .article-info {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 5px;
    }


    /* Updated Bottom Sliding Images */
    .image-wrapper-container {
        overflow: hidden;
        position: relative;
        width: 100%;
    }

    .image-wrapper {
        display: flex;
        transition: transform 1s ease;
        /*width: fit-content; /* Fit content dynamically */
        width: auto;
    }

    .sliding-image {
        flex: 0 0 33.3333%; /* Adjust width to fit 3 images at a time */
        max-width: 500px;
        object-fit: cover;
    }
    </style>

</main>
@include('sections.footer')
@endsection




{{-- 
    <main id="training-events">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h2>Recent Training</h2>
                    <div id="event-cards">
                        @foreach ($events as $key => $event)
                            <div class="card mb-3">
                                <img src="{{ asset('images/' . $event['image']) }}" class="card-img-top" alt="{{ $event['name'] }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ $event['name'] }}</h5>
                                    <p class="card-text">{{ $event['brief'] }}</p>
                                    <a href="#" class="btn btn-primary learn-more" data-index="{{ $key }}">Learn More</a>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="col-lg-9">
                    <div id="additional-content-slider">
                        @foreach ($events as $event)
                            <div class="additional-content">
                                <h2>{{ $event['name'] }}</h2>
                                <p>Written by {{ $event['name'] }}</p>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </main> --}}
{{-- 
    <main>
        <div class="container">
            <div class="col-lg-12">
                <div class="row">
                    <h1 class="p-5" style="text-align: center;">Page under construction</h1>
                    <img src="{{ asset('storage/asset/under_construction.png') }}" alt="under construction" style="display: block; margin-left: auto; margin-right: auto; width: 500px;">
                </div>
            </div>
        </div>
    </main>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.learn-more').click(function() {
                var index = $(this).data('index');
                $('#additional-content-slider').slick('slickGoTo', index);
            });

            $('#additional-content-slider').slick({
                slidesToShow: 1,
                slidesToScroll: 1,
                arrows: false,
                fade: true,
                asNavFor: '#event-cards'
            });
        });
    </script>
@endsection --}}

